_BASE_: ../../third_party/Mask2Former/configs/cityscapes/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k.yaml
DATASETS:
  TRAIN: ("cosec_day_train",)
  TEST: ("cosec_day_val", "cosec_night_val")
MODEL:
  WEIGHTS: "work_dirs/swinL_cosec_dayonly_from_day65_freeze_backbone_lr5e-7/best_model_cosec_day.pth"
  TRAINABLE_PREFIXES: ["sem_seg_head."]
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0000001
  AMP:
    ENABLED: True
TRAIN:
  EPOCHS: 3
  NUM_TRAIN_SAMPLES: 1917
  EVAL_EVERY_EPOCH: True
  CHECKPOINT_EVERY_EPOCH: True
INPUT:
  MIN_SIZE_TRAIN: [512, 624, 768]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 624
  MAX_SIZE_TEST: 1200
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
DATALOADER:
  NUM_WORKERS: 10
OUTPUT_DIR: "work_dirs/day-exp10a_continue_dayonly65_43_semseg_lr1e-7_bs4"
