MODEL:
  META_ARCHITECTURE: "MaskDINO"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "pretrained/maskdino_swinl_50ep_300q_hid2048_3sd1_panoptic_58.3pq.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 19
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 2048
    NUM_FEATURE_LEVELS: 4
    TOTAL_NUM_FEATURE_LEVELS: 5
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res2", "res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    FEATURE_ORDER: "low2high"
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    BOX_WEIGHT: 0.0
    GIOU_WEIGHT: 0.0
    COST_CLASS_WEIGHT: 4.0
    COST_MASK_WEIGHT: 5.0
    COST_DICE_WEIGHT: 5.0
    COST_BOX_WEIGHT: 0.0
    COST_GIOU_WEIGHT: 0.0
    BOX_LOSS: False
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    EVAL_FLAG: 1
    INITIAL_PRED: True
    TWO_STAGE: True
    DN: "seg"
    DN_NUM: 50
    INITIALIZE_BOX_TYPE: "no"
    PANO_BOX_LOSS: False
    SEMANTIC_CE_LOSS: True
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
DATASETS:
  TRAIN: ("cosec_train", "dsec19_train_filtered630", "acdc_all_train")
  TEST: ("cosec_day_val", "cosec_night_val", "acdc_all_val", "acdc_night_val")
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.00002
  MAX_ITER: 24000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.01
  CHECKPOINT_PERIOD: 200
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: [384, 448, 512, 576, 640]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 768
  MAX_SIZE_TRAIN: 1536
  MAX_SIZE_TEST: 1536
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (384, 768)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: -1
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 500
  AUG:
    ENABLED: False
    MIN_SIZES: [512, 768, 1024]
    MAX_SIZE: 1536
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
OUTPUT_DIR: "work_dirs/maskdino_swinl_cosec_dsec_acdc_safe_bs1"
VERSION: 2
